// constants.js

const ADD_PERSON = 'ADD_PERSON';
const DELETE_PERSON = 'DELETE_PERSON';
const FETCH_PEOPLE = 'FETCH_PEOPLE';
const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS';
const FETCH_PEOPLE_FAILURE = 'FETCH_PEOPLE_FAILURE';

export {
  ADD_PERSON,
  DELETE_PERSON,
  FETCH_PEOPLE,
  FETCH_PEOPLE_SUCCESS,
  FETCH_PEOPLE_FAILURE,
};
